spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa


resilience4j.circuitbreaker:
  instances:
    service2:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 3
      ringBufferSizeInHalfOpenState: 1
      waitDurationInOpenState: 2s
      failureRateThreshold: 50
      recordExceptions:
        - com.thoughtworks.exceptions.DependencyException

    service1:
      slidingWindowSize: 4
      permittedNumberOfCallsInHalfOpenState: 4
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - com.thoughtworks.exceptions.DependencyException



resilience4j.retry:
  instances:
    service1:
      maxRetryAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 1
      retryExceptions:
        - com.thoughtworks.exceptions.DependencyException
      ignoreExceptions:
        - io.github.resilience4j.circuitbreaker.CallNotPermittedException

