spring:
  jpa:
    hibernate.ddl-auto: validate
flyway.enabled: true
flyway.locations: classpath:/db/migration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    show-details: always

resilience4j.circuitbreaker:
  instances:
    bankservice:
      slidingWindowSize: 4
      permittedNumberOfCallsInHalfOpenState: 4
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - com.thoughtworks.exceptions.DependencyException

resilience4j.retry:
  instances:
    bankservice:
      maxRetryAttempts: 3
      waitDuration: 2s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - com.thoughtworks.exceptions.DependencyException
      ignoreExceptions:
        - io.github.resilience4j.circuitbreaker.CallNotPermittedException


Server:
  port: 8080
