spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa


resilience4j.circuitbreaker:
  instances:
    service1:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 3
      ringBufferSizeInHalfOpenState: 1
      waitDurationInOpenState: 2s
      failureRateThreshold: 50
      recordExceptions:
        - com.thoughtworks.exceptions.DependencyException



resilience4j.retry:
  instances:
    service1:
      maxRetryAttempts: 4
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - com.thoughtworks.exceptions.DependencyException
      ignoreExceptions:
        - io.github.resilience4j.circuitbreaker.CallNotPermittedException

