spring:
  jpa:
    hibernate.ddl-auto: validate
flyway.enabled: true
flyway.locations: classpath:/db/migration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    show-details: always

resilience4j.circuitbreaker:
  instances:
    service1:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - com.thoughtworks.exceptions.DependencyException


resilience4j.retry:
  instances:
    service1:
      maxRetryAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - com.thoughtworks.exceptions.DependencyException

Server:
  port: 8080
