spring:
  jpa:
    hibernate.ddl-auto: validate
flyway.enabled: true
flyway.locations: classpath:/db/migration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    show-details: always

resilience4j.circuitbreaker:
  instances:
    service1:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 4
      ringBufferSizeInHalfOpenState: 2
      waitDurationInOpenState: 20s
      failureRateThreshold: 50
      recordExceptions:
        - com.thoughtworks.exceptions.DependencyException
    service2:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - com.thoughtworks.exceptions.DependencyException
Server:
  port: 8080
